name: Build SunamoInterfaces

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoInterfaces
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoInterfaces/SunamoInterfaces.csproj

    - name: Build
      run: dotnet build SunamoInterfaces/SunamoInterfaces.csproj --configuration Release --no-restore

  test:
    name: Test SunamoInterfaces.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoInterfaces.Tests/SunamoInterfaces.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoInterfaces.Tests/SunamoInterfaces.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoInterfaces.Tests/SunamoInterfaces.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
